# Generated by Django 3.1.3 on 2021-01-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0002_auto_20210111_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
