# Generated by Django 3.1.3 on 2021-01-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0003_article_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='others',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
