# Generated by Django 3.1.3 on 2021-01-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0004_auto_20210112_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
