# Generated by Django 3.0.4 on 2020-03-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winkelapp', '0002_products_prod_sprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prod_offer',
            field=models.BooleanField(default=False),
        ),
    ]
