# Generated by Django 3.0.3 on 2020-05-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('menu_desc', models.CharField(max_length=100)),
                ('menu_image', models.FileField(upload_to='')),
                ('menu_price', models.PositiveIntegerField()),
            ],
        ),
    ]
