# Generated by Django 3.0.3 on 2020-05-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_image',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
